ci: check if project exist

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -24,7 +24,11 @@ jobs:
             
         - name: Clone Bitbucket repository
           run: |
-            git clone git@bitbucket.org:adaptavistlabs/salable-api.git
+            git clone ${{ vars.SALABLE_API_REPO_URL }}
+            if [ ! -d "salable-api" ]; then
+                echo "Error: Directory 'salable-api' does not exist."
+                exit 1
+            fi
             
         - name: Build and deploy
           env: 
